<?php

/**
 * @file
 * Contains og_block_accordion.module.
 */

/**
 * Implements hook_theme().
 */
function og_block_accordion_theme($existing, $type, $theme, $path) {
  return [
    'block__og_block__accordion' => [
      'base hook' => 'block',
      'render element' => 'elements',
      'template' => 'accordion',
    ],
  ];
}

/**
 * Implements hook_preprocess_block().
 */
function og_block_accordion_preprocess_block__og_block__accordion(&$variables) {
  if (isset($variables['elements'])) {
    if (isset($variables['elements']['#configuration']['block_revision_id'])) {
      $block_id = 'accordion-' . $variables['elements']['#configuration']['block_revision_id'];
    }
    else {
      $id = explode(":", $variables['elements']['#configuration']['id']);
      if (is_array($id) && isset($id[1])) {
        $block_id = 'accordion-' . $id[1];
      }
    }

    $variables['block_id'] = $block_id;

    $variables['#attached']['library'][] = 'og_block_accordion/accordion';
  }
}
