<?php

/**
 * @file
 * Contains og_block_callout_text.module.
 */

use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;

/**
 * Implements hook_theme().
 */
function og_block_callout_text_theme($existing, $type, $theme, $path) {
  return [
    'block__og_block__callout_text' => [
      'base hook' => 'block',
      'render element' => 'elements',
      'template' => 'callouttext',
    ],
  ];
}

/**
 * Implements hook_preprocess_block().
 */
function og_block_callout_text_preprocess_block__og_block__callout_text(&$variables) {
  $block = $variables['content']['#block_content'];
  if ($block instanceof \Drupal\block_content\BlockContentInterface) {
    $blockquote = [];
    if ($value = $block->field_callout_text_normal_1->value) {
      $blockquote[] = [
        'content' => [
          '#markup' => $value.' ',
        ]
      ];
    }

    if ($value = $block->field_callout_text_accent->value) {
      $blockquote[] = [
        'content' => [
          '#markup' => '<span class="accent">'.$value.'</span> ',
        ]
      ];
    }

    if ($value = $block->field_callout_text_normal_2->value) {
      $blockquote[] = [
        'content' => [
          '#markup' => $value,
        ]
      ];
    }

    $variables['data']['blockquote'] = $blockquote;
  }
}
