<?php

/**
 * @file
 * Contains og_block_contact.module.
 */

use Drupal\block_content\Entity\BlockContent;
use Drupal\config_pages\Entity\ConfigPages;

/**
 * Implements hook_theme().
 */
function og_block_contact_theme($existing, $type, $theme, $path) {
  return [
    'block__inline_block__contact' => [
      'base hook' => 'block',
      'render element' => 'elements',
      'template' => 'contact',
    ],
    'block__og_block__contact' => [
      'base hook' => 'block',
      'render element' => 'elements',
      'template' => 'contact',
    ],
  ];
}


/**
 * Implements hook_preprocess_block().
 */
function og_block_contact_preprocess_block(&$variables) {
  if (isset($variables['content']['#block_content'])) {
    /** @var Drupal\block_content\Entity\BlockContent $block_content */
    $block_content = $variables['content']['#block_content'];

    if ($block_content->bundle() === 'contact') {
      $variables['#attached']['library'][] = 'og_block_contact/contact';
      if (isset($variables['elements']['#configuration']['block_revision_id'])) {
        $block_id = 'contact-' . $variables['elements']['#configuration']['block_revision_id'];
      }
      else {
        $id = explode(":", $variables['elements']['#configuration']['id']);
        if (is_array($id) && isset($id[1])) {
          $block_id = 'contact-' . $id[1];
        }
      }
      $variables['block_id'] = $block_id;
      $variables['attributes']['id'] = $block_id;

      // Load label text
      /** @var ConfigPages $site_settings */
      $site_settings = ConfigPages::config('site_settings');
      $labelkey = [
        'field_contact_web' => 'field_weblabel', 'field_contact_mobile' => 'field_mobilelabel',
        'field_contact_phone' => 'field_phonelabel', 'field_contact_email' => 'field_emaillabel',
        'field_contact_name' => 'field_contactlabel',
      ];
      foreach ($labelkey as $block_field => $config_field) {
        if (!$site_settings->get($config_field)->isEmpty()) {
          $variables['content'][$block_field]['#title'] = $site_settings
            ->get($config_field)->value;
        }
      }

      // Schema.org
      $variables['title_attributes']['property'] = 'name';
      $variables['attributes']['vocab'] = 'https://schema.org/';
      $variables['attributes']['typeof'] = 'Organization';
      if (isset($variables['content']['field_contact_web'][0])) {
        $variables['content']['field_contact_web'][0]['#attributes']['property'] = 'url';
        $variables['content']['field_contact_web'][0]['#attributes']['target'] = '_blank';
      }
    }
  }
}
